CREATE DATABASE login_db;

USE login_db;

CREATE TABLE users(
    id INT(11) NOT NULL,
    username VARCHAR(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    rol VARCHAR(50) NOT NULL,	
    password VARCHAR(60) NOT NULL
);

ALTER TABLE users
    ADD PRIMARY KEY (id);

ALTER TABLE users
	MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 2; 


DESCRIBE users;
